### ISSUE TITLE
Inherit version from Spring Boot's dependency management

### ISSUE THREAD

**Issue by mp911de** [lankydan/spring-data-cassandra#1]
Dependencies managed by Spring Boot are not required to specify a version number. In fact, that can cause issues because other Spring Data dependencies are managed too and can cause compatibility issues.

https://github.com/lankydan/spring-data-cassandra/blob/13f6e7184752856ed7578629f287a29c043afb7a/pom.xml#L38

**Comment by lankydan** [comment]
Cool, I'll try remove it when I can.
