### ISSUE TITLE
Consider using Spring Boot's auto configuration

### ISSUE THREAD

**Issue by mp911de** [lankydan/spring-data-cassandra#2]
Wide parts of the config are already provided by Spring Boot (contact points, schema actions, enabling reactive repositories). The only feature not provided by Boot is setup/drop of keyspaces. Maybe you want to outline that particular aspect to explain why that is – btw. filing a Boot ticket to customize keyspace creation/drop is never a bad idea 😸 

https://github.com/lankydan/spring-data-cassandra/blob/13f6e7184752856ed7578629f287a29c043afb7a/src/main/java/com/lankydan/cassandra/CassandraConfig.java#L14-L69

**Comment by lankydan** [comment]
I know that I didn't need to set things like the contact points, port etc, but I probably should of removed them from this branch being I didn't explain why they were there in my post. 

How are the reactive repositories enabled by auto config? 

Luckily I wrote a post about the creation/dropping of keyspaces where I explained it, just added it to this one to make it easier to use but not focus too much on it.

**Comment by mp911de** [comment]
Take a look at [`CassandraReactiveRepositoriesAutoConfigureRegistrar`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/cassandra/CassandraReactiveRepositoriesAutoConfigureRegistrar.java#L53).

**Comment by lankydan** [comment]
Thanks will do
